version: "3.8"

x-build: &dockerfile-dev-build
  context: .

services:
  tests:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command:
      [
          "./scripts/start-tests.sh",
      ]
  lint:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command:
      [
          "./scripts/start-lint.sh",
      ]
  formatter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command:
      [
          "./scripts/start-formatter.sh",
      ]
  sonarcloud:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command:
      [
          "./scripts/start-sonarcloud.sh",
          "YOUR-SONAR-CLOUD-TOKEN",
          "YOUR-PROJECT-VERSION",
      ]
  publish-package:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command:
      [
          "./scripts/start-nuget.sh",
          "YOUR-API-KEY",
      ]
