name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.sln'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install dotnet-format and dotnet-sonarscanner
        run: |
          dotnet tool install --global dotnet-format
          dotnet tool install --global dotnet-sonarscanner
      - name: Check if the project is well formatted
        run: |
          ./scripts/start-lint.sh
      - name: Build the project, run all tests and publish to SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        
        run: |
          ./scripts/start-sonarcloud.sh ${{ secrets.SONAR_TOKEN }} ${{ github.sha }}
